version: "3.8"

services:
  frontend:
    build:
      context: ./ 
    container_name: til-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://qazaqtil.ip-ddns.com/api/v1
